Built in library

NumPy - numerical computing
Pandas - data handling
Matplotlib - data visualisation

#NumPy Basic NumPy provides fast mathematical operation

In [8]:
import numpy as np

In [9]:
arr1 = np.array(2)
print(arr1)

2


In [12]:
arr2 = np.array([1,2,3,4,5,6,7])
print(arr2)
print(arr2.ndim)

[1 2 3 4 5 6 7]
1


#2D array

In [13]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.ndim)

[[1 2 3]
 [4 5 6]]
2


#3D array

In [14]:
arr4 = np.array([[1,2],[3,4],[5,6]])
print(arr4)
print(arr4.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [19]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.shape

(5,)

Panda

In [4]:
import pandas as pd

In [12]:
#Creating a series
s = pd.Series([1,2,3,4,5], name = 'numbers')
print(s)

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: int64


In [18]:
 #Creating a Data frame
df = pd.DataFrame( {'A':[ 1, 2, 3], 'B':['a', 'b', 'c'], 'C':[4.5, 5.5, 6.5] } )
print(df)

   A  B    C
0  1  a  4.5
1  2  b  5.5
2  3  c  6.5


Data Manipulation

In [31]:
#Accessiing a specific value
value = df.loc[ 0, 'C']
print(value)

# Selecting multiple columns
selected_columns = df.loc[:, ['A', 'C']]
print("\n",selected_columns)

# Selecting a range of rows
selected_rows = df.loc[ 2:3, :]
print("\n",selected_rows)

#Selecting both
scol = df.loc[ 0:1, ['A', 'C']]
print("\n",scol)

4.5

    A    C
0  1  4.5
1  2  5.5
2  3  6.5

    A  B    C
2  3  c  6.5

    A    C
0  1  4.5
1  2  5.5


In [37]:
#Filtering rows based on condition
filtered_df = df[ df['A'] > 2]
print(filtered_df)

#Filtering rows based on multiple conditions
filtered_df = df[ ( df['A'] > 1 ) & ( df['C'] < 6 ) ]
print("\n",filtered_df)

   A  B    C
2  3  c  6.5

    A  B    C
1  2  b  5.5


Data cleaning

In [3]:
import pandas as pd
import numpy as np

#Creating a DataFrame with missing values
df = pd.DataFrame( {
    'A':[1, 2, np.nan, 4],
    'B':[np.nan, 'b', 'c', 'd'],
    'C': [4.5, np.nan, 6.5, 7.5]
} )

#Detecting missing values
missing_values = df.isna()
print(missing_values)

       A      B      C
0  False   True  False
1  False  False   True
2   True  False  False
3  False  False  False


In [4]:
#Filling missing data with a specific value
filled_df = df.fillna(-1)
print(filled_df)

     A   B    C
0  1.0  -1  4.5
1  2.0   b -1.0
2 -1.0   c  6.5
3  4.0   d  7.5


Transforming a dataframe

In [8]:
#Creating a DataFrame for traansformation example
df = pd.DataFrame( {
    'A':[1, 2, 3, 4], 
    'B':[10, 20, 30, 40]
} )

#Applying a transformation function
transformed_df = df.apply(lambda x: x * 4)
print(transformed_df)

    A    B
0   4   40
1   8   80
2  12  120
3  16  160


Data input and output

In [ ]:
import pandas as pd

#Reading data in CSV files
df_csv = pd.read_csv('sample.csv')
print(df_csv)

#Reading data from an Excel file
df_excel = pd.read_excel('sample.xlsx')
print(df_excel)

In [ ]:
#Writing Data in a CSV file
df = pd.DataFrame({
    'Name' : ['Alice', 'Bob', 'Carol'],
    'Age': [24, 30, 28],
    'City' : ['New York', 'Los Angles', 'Chicago']
})

df.to_csv('output.csv', index = False)